export const FETCH_TOKEN_REQUEST = 'FETCH_TOKEN_REQUEST';
export const FETCH_TOKEN_SUCCESS = 'FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_FAILURE = 'FETCH_TOKEN_FAILURE';
export const FETCH_NEW_RELEASES_REQUEST = 'FETCH_NEW_RELEASES_REQUEST';
export const FETCH_NEW_RELEASES_SUCCESS = 'FETCH_NEW_RELEASES_SUCCESS';
export const FETCH_NEW_RELEASES_FAILURE = 'FETCH_NEW_RELEASES_FAILURE';
export const SET_NEW_RELEASES_OFFSET = 'SET_NEW_RELEASES_OFFSET';